
[Audio]
DSPEmulation = "null"
EnableAudio = false

[Battery]
BatteryPercentage = 3
ChargerPlugged = true

[GPU]
AccurateShaderMultiplication = false
EnableRenderdoc = false
EnableShaderJIT = true
EnableVSync = true
ForceShadergenForLighting = true
Renderer = "opengl"
ShadergenLightThreshold = 1
UseUbershaders = false

[General]
AppVersionOnWindow = false
DefaultRomPath = ""
EnableDiscordRPC = false
PrintAppVersion = true
UsePortableBuild = false

[SD]
UseVirtualSD = true
WriteProtectVirtualSD = false

